{{ if eq .Environment "production" }}
apiVersion: zalando.org/v1
kind: PlatformCredentialsSet
metadata:
  name: "kube-metrics-adapter"
  namespace: kube-system
  labels:
    application: "kube-metrics-adapter"
spec:
  application: "kube-metrics-adapter"
  tokens:
    zmon:
      privileges: []
{{ end }}
