{{ if eq .Environment "production" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emergency-access-service
  namespace: kube-system
  annotations:
    zalando.org/skipper-filter: |
      oauthTokeninfoAnyScope("uid")
  labels:
    application: emergency-access-service
spec:
  rules:
  - host: emergency-access-service.{{ .Alias }}.zalan.do
    http:
      paths:
      - backend:
          serviceName: emergency-access-service
          servicePort: http
{{ end }}
