kind: Service
apiVersion: v1
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    application: external-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "ExternalDNS"
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "7979"
    prometheus.io/scrape: "true"
spec:
  selector:
    application: external-dns
  type: ClusterIP
  ports:
  - name: monitor
    port: 7979
    targetPort: 7979
    protocol: TCP
