apiVersion: v1
kind: Service
metadata:
  labels:
    application: kubernetes-lifecycle-metrics
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  name: kubernetes-lifecycle-metrics
  namespace: kube-system
spec:
  selector:
    application: kubernetes-lifecycle-metrics
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
