kind: Service
apiVersion: v1
metadata:
  name: skipper-internal
  namespace: kube-system
  labels:
    application: skipper-ingress
spec:
  type: ClusterIP
  clusterIP: 10.3.99.99
  ports:
    - port: 80
      targetPort: 9999
      protocol: TCP
  selector:
    application: skipper-ingress
